PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX picom: <https://personsincontext.org/model#>
PREFIX sdo: <https://schema.org/>
PREFIX picot_roles: <https://terms.personsincontext.org/roles/>

CONSTRUCT {
	?bride picom:hasUncle_Aunt ?witness .
    ?witness sdo:gender sdo:Male .
}
WHERE {
    ?witness a picom:PersonObservation ;
    	prov:hadPrimarySource ?src ;
    	sdo:description ?desc .
    FILTER(CONTAINS(?desc, "relatie tot de bruid: oom"))
    ?bride a picom:PersonObservation ; 
    	prov:hadPrimarySource ?src ;
    	picom:hasRole picot_roles:574 ;
    	sdo:gender sdo:Female .
}